### ISSUE TITLE
before_action doesn't work

### ISSUE THREAD

**Issue by FNGR2911** [nsarno/knock#100]
hey everybody! I can't get the before action to work with my rails (5.0.0.1) API. I have namespaced routes (api/v1) so my application_controller looks like:

```ruby
class ApplicationController < ActionController::API
  include Knock::Authenticable
  include ActionController::Serialization

  private
    def authenticate_api_user
      authenticate_for Api::V1
    end
end
```

my user_controller looks like:
```ruby
class Api::V1::UsersController < ApplicationController
  before_action :authenticate_api_user

  def index
      render json: User.all
  end
end
```

So, when I try to GET the index action it just works! without any authorization.

```bash
Started GET "/api/v1/users/" for 127.0.0.1 at 2016-08-29 16:15:12 +0200
Processing by Api::V1::UsersController#index as HTML
  User Load (0.3ms)  SELECT "users".* FROM "users"
[active_model_serializers] Rendered ActiveModel::Serializer::CollectionSerializer with ActiveModelSerializers::Adapter::Attributes (0.37ms)
Completed 200 OK in 13ms (Views: 7.2ms | ActiveRecord: 0.8ms)
```

So any ideas what I've done wrong? thank you guys!

EDIT
okay, I figured out just using before_action `:authenticate_user `works?! is that okay?

**Comment by nsarno** [comment]
Using `authenticate_for` in a `before_action` is only required in the case where you have a namespaced model. Namespaced routes should not have any impact.

**Comment by FNGR2911** [comment]
Oh okay, thanks for clarification :) (my first API ;))

**Comment by nsarno** [comment]
No worries 👍

**Comment by jasonswett** [comment]
So to be clear, the following is what worked, right?

```ruby
class Api::V1::UsersController < ApplicationController
  before_action :authenticate_user

  def index
    render json: User.all
  end
end
```
