### ISSUE TITLE
Release a gem version with PR #84 included.

### ISSUE THREAD

**Issue by samueldr** [nsarno/knock#102]
I happened to have the same issue that #99 had with Knock, where the first request worked, but not subsequent requests, until code was reloaded.

[This PR](https://github.com/nsarno/knock/pull/84) fixed the issue, but there is no release yet including this fix.

Temporarily using the `~>1.4.2` [pessimistic version constraint](http://guides.rubygems.org/patterns/#pessimistic-version-constraint) works for me, but I'd much rather prefer using `~>1.5.1` or something like that that would include the fix (assuming the fix does work).

**Comment by Rodeoclash** [comment]
@samueldr Installing from master: `gem 'knock', github: 'nsarno/knock'` fixed the reload issue for me - if you don't want to fall back to 1.4.2

**Comment by nsarno** [comment]
@samueldr I was hoping to do this sooner but haven't taken the time to get to it yet. Thank you guys for being patient :)
