### ISSUE TITLE
Using with password-less authentication

### ISSUE THREAD

**Issue by oyeanuj** [nsarno/knock#105]
Hi @nsarno! Thank you for open sourcing this library! I was running into a conceptual problem while using it in a password-less authentication model (tldr: user enters email, clicks on link in sent email to authenticate - all of which is already set up).

I was curious as to how best to implement the `authenticate` method that the model needs to support. It seems like it is being used here and the password field is being sent: https://github.com/nsarno/knock/blob/d78f2481d86a2acd139d95075c3b181024c320c4/app/controllers/knock/auth_token_controller.rb#L13

It seems that since it was authenticating the password in regular setups, in my case, it would authenticate the email-token sent to check if it is authentic or not. Is that correct? If yes, how do I send that token to the authenticate method since it seems the password is hardcoded to be sent right now.

Also, is my understanding correct that the `user_token#create` is just the route to authenticate, and that if I already have that happening elsewhere, I might not need that route, and instead have that controller inherit from `Knock::AuthTokenController`?

Thank you!

**Comment by oyeanuj** [comment]
edited the question above for clarity.

**Comment by nsarno** [comment]
I haven't tried to implement this myself so I can only guess what I would try to do myself.

For the initial token creation, I see two possible solutions:

- Pass the token from the email via the `auth[password]` param and implement your own `User.authenticate` method

or

- Implement your own authentication controller that does whatever you want and returns the auth token (with `AuthToken.new payload: { sub: entity.id }`)

> Also, is my understanding correct that the user_token#create is just the route to authenticate

Yes. This is a route that would be generated when you run the generator:

`rails generate knock:token_controller user`

If you implement your own route and controller to create the token, then you don't need this.
