### ISSUE TITLE
Angular Integration

### ISSUE THREAD

**Issue by OpticNectar** [nsarno/knock#106]
Is there a good article or add on that can connect this gem with Angular? I've found things like https://github.com/lynndylanhurley/ng-token-auth etc, but i'm not 100% sure how to integrate it since there seem to be a lot of functions missing.

**Comment by nsarno** [comment]
Not that I know of sorry. I haven't used angular in a while but integrating with Knock should be straightforward. I'm closing this as this isn't an issue per se, but feel free to contribute by adding a link to an article or some similar resource that would help with this. Thanks!
