### ISSUE TITLE
integration with lock

### ISSUE THREAD

**Issue by bdavidxyz** [nsarno/knock#108]
Is there any way to integrate knock with [lock](https://auth0.com/docs/libraries/lock/v10/auth0js) ? Since knock works seamlessly with auth0, it would be great to have also a seamless ui integration, regardless of how the ui is built (vanillaJS, jQuery, angular, ember, or whatever)

**Comment by bdavidxyz** [comment]
Maybe in-depth study of https://github.com/nsarno/knock/issues/103 should solve the issue

**Comment by nsarno** [comment]
I don't know as I never used lock myself. I'm closing this as this is not an issue per se, but feel free to contribute by adding an example of how to integrate it if you'd like.
