### ISSUE TITLE
Best way to refresh a JWT token, which is about to expire.

### ISSUE THREAD

**Issue by flowryaan** [nsarno/knock#109]
Hello everyone 😊

First of all I am sorry if this is a stupid question. I am just learning all the things about securing APIs. I know that tokens should not be valid forever, so the tokens should have a short expiration time, but this raises a problem on how to refresh a token.

I was thinking about something like requesting the `/user_token` route (which knock provides) with the `Authorization` Header with a valid token set, instead of providing login information and also getting a new JWT token back, but the only option seems that this route is for "logging in" only.

Is a feature like this already implemented with knock or do I have to write it myself? Also is this a valid way to refresh a token or are there better ways?

Thanks in advance

**Comment by nsarno** [comment]
@flowryaan A similar topic has already been discussed in #65. Hope this helps!
