### ISSUE TITLE
Is there any guide like for 

### ISSUE THREAD

**Issue by saroar** [nsarno/knock#112]
omniauth-facebook with knock ? for api server site so click site can us for Facebook login 
please let me know or some guide with Auth0.
i need open source

**Comment by muZk** [comment]
Hey, I was playing a bit with this gem and facebook login. I created a sample rails API application with my experiment available at https://github.com/muZk/rails5-api-jwt-facebook-auth

Note: the approach doesn't require omniauth (btw, I'm not sure if its the best approach).

**Comment by saroar** [comment]
thanks a lot i will check tomorrow thanks again i will play with it
