### ISSUE TITLE
N+1 Queries For current_user

### ISSUE THREAD

**Issue by duboff** [nsarno/knock#115]
Every time I try something like:
```rb
current_user.charts
```

Where a charts is another model with a many to many relationship with the user. In a controller, `bullet` gem alerts me there is an N+1 query:
```sh
N+1 Query detected
  User => [:charts]
  Add to your finder: :includes => [:charts]
```

I can usually get around this by doing `Chart.where(user: current_user)` but this is a lot less pleasant to work with.

Is there something simple I am missing or does current implementation of `current_user` prevents us from optimizing performance?

**Comment by ristovskiv** [comment]
The current implementation of the `current_user` method is nothing but `User.find(id)` that is if everything is set as default and nothing is overridden or changed in the configuration file. So my humble opinion is that `current_user` is not causing the N+1 queries. Have you tried `current_user.includes(:charts)` and then access the attributes from the charts relationships ?

**Comment by bortevik** [comment]
`User.find(id).includes(:relationship)` doesn't work. It should be `User.includes(:relationship).find(id)`

**Comment by ristovskiv** [comment]
Yeah you are absolutely right, sorry about it. my beginners mistake... :(

**Comment by duboff** [comment]
Yeah, the problem is it's hard to chain `includes` onto a `current_user` as currently designed.

**Comment by nsarno** [comment]
@duboff You can use `.from_token_payload` to solve this.

e.g.

```
class User

  def self.from_token_payload payload
    User.includes(:relationship).find(payload["sub"])
  end
```

Let me know if this solves your issue and feel free to re-open if not. Thank you!

**Comment by duboff** [comment]
Hi @nsarno, this does help but that now means I have to eager load the relationship everywhere which is not ideal either. Typically you only need the relationship in each controller.

I also can't (as far as I can figure out) reimplement the current_user method. Maybe it would make sense to pass relationships to it as an argument? Happy to try that myself if you think it makes sense.

**Comment by nsarno** [comment]
@duboff You should be able to define your own `current_user` method. Knock checks if the method is already implemented before defining it.

Also I don't really think this qualify as a N+1 query in the sense where N will always equal to 1 in this instance (which Bullet can't know about). So the impact should never be significant and might not require the extra optimization work. This is of course up to you to assess.

As far as Knock is concerned, I don't believe it's worth the extra lines of code.
