### ISSUE TITLE
Multiple User Types

### ISSUE THREAD

**Issue by colinramsay** [nsarno/knock#119]
We have both `admin` and `user` types but these are stored in separate tables. We'd like both types to be able to log in using the same mechanism. It seems that knock doesn't really lend itself to having this arrangement - is there any recommended way of doing this?

**Comment by nsarno** [comment]
Have you read the README? Knock allows you to use any user type that you want side by side, out of the box. The example is even given specifically for `admin`.

Let me know if I misunderstood your question or if you find the README isn't clear enough.

**Comment by colinramsay** [comment]
I have read the readme; I'm using knock in production. What I want is that `current_user` would return either `User` or `Admin` depending on who is logged in. I've got a workaround in place anyway.

**Comment by mckayward** [comment]
For future readers, the owner's comments on PR https://github.com/nsarno/knock/pull/16 provide insight into this use case, including a suggested solution.
