### ISSUE TITLE
Allow passing auth_params as a whole to authenticate (v2)

### ISSUE THREAD

**Issue by anthonator** [nsarno/knock#12]
This would give the implementer the freedom to implement `authenticate` how they choose. I may want to pass additional information to `authenticate` or provide a password-less authentication mechanism.

Granted, it looks like you're trying to adhere to the interface that `has_secure_password` provides, but there are many use cases where this doesn't work. So making it a configurable option might make sense.

**Comment by anthonator** [comment]
or an even easier approach, document the `authenticate` controller method and inform people how to override.

**Comment by nsarno** [comment]
The auth token controller that knock provides is oriented towards a solution based on `has_secure_password` as this is what people will try to implement most of the time.

In the v2, as of now, the auth token is generated per user model with the following command:

```bash
$ rails g knock:token_controller user
```

This will generate `app/controllers/user_token_controller.rb`:

```ruby
class UserTokenController < Knock::AuthTokenController
end
```

So if your authentication mechanism is something really different, a better option is to override the `create` method here and you will have all the flexibility that you need: access to params, the request headers etc.

Here's an idea of how you could do it:

```ruby
class UserTokenController

  # `authenticated?` and `user` are also methods you would have to implement yourself.
  def create
    if authenticated?
      render json: AuthToken.new(payload: { sub: user.id })
    else
      head :not_found
    end
  end
end
```

In the end, you can implement the `create` method however you wish. As long as you respond with a JWT token. And you can still benefit from the token validation features provided by knock.

**Comment by nsarno** [comment]
I just added a `to_json` method to `AuthToken` so the example code above is valid.

**Comment by nsarno** [comment]
Also if you implement a generic solution to authenticate from OAuth (or something else), it would be great to add it directly to knock.

It could look something like this (not sure about the naming but this is just a general idea):

```bash
$ rails g knock:oauth_strategy
```

generates `app/controllers/user_token_controller.rb`:
```ruby
class UserTokenController < Knock::OAuthStrategyTokenController
end
```

**Comment by nsarno** [comment]
As you suggested, I actually need to document this for the V2. So I reopen the issue until it's done.

Thank you for the feedback.

**Comment by anthonator** [comment]
Here's what I came up with for my own use case. All I really needed was the ability to define my own authentication strategy rather than being shoehorned into a predefined one defined by `has_secure_password`. I think this provides the ultimate flexibility.

I'd call this the **Bring Your Own Strategy** strategy.

```ruby
class UserTokenController < Knock::AuthTokenController
  private

  def authenticate
    @resource = JWT::Authenticate.call(auth_params, cookies)

    head :unauthorized unless @resource
  end

  def resource; @resource end
end
```

**Comment by nsarno** [comment]
Although this is perfectly fine, I would rather advertise overriding the `create` method as still using `Knock::AuthTokenController` in this case makes your code harder to understand and only saves you ~5 loc.

**Comment by anthonator** [comment]
Sorry if I'm being dense but I'm not following. Even if I override the `create` method won't I still be using the `Knock::AuthTokenController`? Are you talking about another controller that doesn't subclass `Knock::AuthTokenController`?

**Comment by nsarno** [comment]
No worries.

If you provide your own `create` method, you don't need to inherit from `Knock::AuthTokenController`. I should not have talked about "overriding" because all you do is provide your own controller. Sorry if that got you confused.
