### ISSUE TITLE
Case-insensitive email comparison?

### ISSUE THREAD

**Issue by atomanyih** [nsarno/knock#131]
It would be nice to have the option to look up and authenticate a user via `email` regardless of case. 

Technically only the "local part" of the email is case-sensitive, but a lot of systems are case-insensitive to the entire email (both local part and domain). Devise lets you configure this in the initializer: https://github.com/plataformatec/devise/wiki/How-To:-Use-case-insensitive-emails

It doesn't have to be a default but a built-in solution would be nicer than overriding `auth_params`:
```ruby
def auth_params
  auth_params = params.require(:auth).permit :email, :password
  auth_params[:email].downcase!
  auth_params
end
```

or putting `from_token_request` on your model

**Comment by johnunclesam** [comment]
Which is the best way? Override `auth_params` (and how the best? Initializer?) or use `from_token_request` on my model? Can you please explain us this, @nsarno? Thanks.

**Comment by nsarno** [comment]
I'm trying to stay away from configuration as much as possible in favour of sensible defaults and a way to override it.

In this instance, using `.from_token_request` is a perfectly suitable solution.

I'm not too sure about what would be the best default but email addresses are case sensitive (except for the domain), so the current behaviour seems appropriate.

I'll close this issue, but feel free to re-open it if you think of a better default or if you believe the use of `.from_token_request` isn't suitable for some reason. Thanks!
