### ISSUE TITLE
Auth param missing

### ISSUE THREAD

**Issue by GregTheGreek** [nsarno/knock#132]
I'm running a rails 5 API and posting to the knock engine to generate a JWT token.

I haven't modified the knock code and for whatever reason params being passed to the controller do not include `auth` even though I have it in the payload...

Anyone else have this issue?

**Comment by GregTheGreek** [comment]
This is not a knock error. Im using axios for ReactJS .. it was an axios error.

**Comment by johnunclesam** [comment]
How to modify the "auth" word? What if I don't want an "auth" param?

**Comment by zangab** [comment]
then you would have to override / customize the classes for your needs - but whats annoying about the "auth" param?

**Comment by zangab** [comment]
@GregTheGreek would you close the issue cause its not an error of the gem knock

**Comment by johnunclesam** [comment]
@zangab can you please post an example for authentication without "auth" param?

**Comment by zangab** [comment]
you could create a file in `config/initializers` (naming doesnt matter, but maybe smth like `custom_token_auth.rb`) and put this code into it:
```
Knock::AuthTokenController.class_eval do

  private
    def auth_params
      # instead of params.require(:auth).permit :email, :password
      # you would need to
      params.permit :email, :password
    end
end
```
restart the server and it should work with:
```
{
    "email": "address@host.domain",
    "password": "jkdlajlkfa"
}
```

**Comment by johnunclesam** [comment]
Which is the best way? Override `auth_params` like this or use from_token_request on my model?
Can you please explain this.

Why `class_eval`?

**Comment by zangab** [comment]
hmmm - I guess both is fine - I can't tell you which one is better.

with `Knock::AuthTokenController.class_eval` you can modify (like override methods) or also extend the class, in this case the `AuthTokenController` in the `Knock` module. I used this to add a custom response value in addition to the token when a user signs up.
[class_eval info](http://apidock.com/ruby/Module/class_eval)

**Comment by nsarno** [comment]
> This is not a knock error. Im using axios for ReactJS .. it was an axios error.

Closing this issue.

**Comment by nsarno** [comment]
@johnunclesam:

> How to modify the "auth" word? What if I don't want an "auth" param?

`.from_token_request` gives you full flexibility to customise this behavior. It would be the recommended way to do it.

**Comment by GregTheGreek** [comment]
@nsarno sorry I would have clsoed this earlier, didn't get email updates.

**Comment by zangab** [comment]
@nsarno how would you return a jwt token when a user signes up? in the `users_controller` i have a `create` method - should this work? (as in the rspec tests)
```
token = Knock::AuthToken.new(payload: { sub: @user.id }).token
```

**Comment by nsarno** [comment]
@zangab yes, this would work.
