### ISSUE TITLE
How to customize user_token response

### ISSUE THREAD

**Issue by zangab** [nsarno/knock#134]
Hy,
I'm using your knock gem in a rails 5 api. My question is, if or how I can modify the method `user_token` to e.g. also return some data the current or authenticated user? (in addition to the jwt)
I guess i could create my own `auth_token_controller.rb` but if there's a simpler / easier way, I would appreciate it.
Thx

**Comment by zangab** [comment]
alright .. I thought this gem is going to be maintained? 🤔😔

however, i solved my own problem by overriding the class method by creating a ruby class in the initializers and with this code:
```
Knock::AuthTokenController.class_eval do

  def create
    render json: {
        jwt: auth_token.token,
        myparam: my_value
      }, status: :created
  end

end
```

**Comment by alfiehub** [comment]
This should be added in my opinion
