### ISSUE TITLE
Auth0 example fails with: `#<NoMethodError: undefined method `verify' for #<String:0x0055d5722781f0>>`

### ISSUE THREAD

**Issue by AugustoPedraza** [nsarno/knock#135]
Hi, I'm following the Auth0 example provides [here](https://auth0.com/docs/quickstart/backend/rails), but I can't make it works because it is failing with the following exception:

#<NoMethodError: undefined method `verify' for #<String:0x0055d5722781f0>>

Backtrace:
```ruby
/home/rails/box/gems/jwt-1.5.6/lib/jwt.rb:61:in `verify_rsa'
/home/rails/box/gems/jwt-1.5.6/lib/jwt.rb:158:in `verify_signature_algo'
/home/rails/box/gems/jwt-1.5.6/lib/jwt.rb:147:in `verify_signature'
/home/rails/box/gems/jwt-1.5.6/lib/jwt.rb:138:in `decode_verify_signature'
/home/rails/box/gems/jwt-1.5.6/lib/jwt.rb:125:in `decode'
/home/rails/box/gems/knock-2.0/app/model/knock/auth_token.rb:11:in `initialize'
/home/rails/box/gems/knock-2.0/lib/knock/authenticable.rb:48:in `new'
/home/rails/box/gems/knock-2.0/lib/knock/authenticable.rb:48:in `block in define_current_entity_getter'
/home/rails/box/gems/knock-2.0/lib/knock/authenticable.rb:5:in `public_send'
/home/rails/box/gems/knock-2.0/lib/knock/authenticable.rb:5:in `authenticate_for'
/home/rails/box/gems/knock-2.0/lib/knock/authenticable.rb:28:in `authenticate_entity'
/home/rails/box/gems/knock-2.0/lib/knock/authenticable.rb:18:in `method_missing'
/home/rails/box/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:382:in `block in make_lambda'
/home/rails/box/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:150:in `block (2 levels) in halting_and_conditional'
```

This is how my initializer looks:

Knock.setup do |config|
  config.token_audience = -> { Rails.application.secrets.auth0_client_id }
  config.token_signature_algorithm = 'RS256'
  config.token_secret_signature_key = -> { Rails.application.secrets.auth0_client_secret }
end

Thanks in advance!!!

**Comment by AugustoPedraza** [comment]
The error was produce because I was using an invalid Auth0 workflow to get my JWT.

**Comment by nsarno** [comment]
@AugustoPedraza Glad you figured it out, thank you for updating the issue.

**Comment by jessecravens** [comment]
@AugustoPedraza can you elaborate on `using an invalid Auth0 workflow to get my JWT` ... I'm seeing the same issue.

**Comment by chandlervdw** [comment]
@AugustoPedraza yes, please elaborate. I'm stumped here, too... I am currently getting my JWT via:
```
curl -X POST \
  __auth0domain__/oauth/token \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/x-www-form-urlencoded' \
  -H 'postman-token: b86c85d5-940d-14d9-a0d1-891813c1f877' \
  -d 'grant_type=client_credentials&client_id=__auth0clientid__&client_secret=__auth0clientsecret&audience=__auth0apiaudience__'
```

**Comment by mottalrd** [comment]
For me the problem was that my code was working under the assumption of using HS256 for the JsonWebToken signature algorithm while on the Auth0 Client advanced settings => OAuth I had specified RS256. I am using the JWT gem for the signature.

My 2 cents :D

**Comment by oamado** [comment]
https://medium.com/@rwehresmann/ruby-on-rails-auth0-knock-7f114ed87e4b This is a good resource
