### ISSUE TITLE
Knock with ActionCable

### ISSUE THREAD

**Issue by brunowego** [nsarno/knock#147]
I wish connect authenticated user with ActionCable, my implementation is below, I have doubts about if is the best approach:

```rb
module ApplicationCable
  class Connection < ActionCable::Connection::Base # :nodoc:
    identified_by :current_user

    def connect
      self.current_user = find_verified_user
    end

    protected

    def find_verified_user
      token = Knock::AuthToken.new token: request.params[:token]

      verified_user = User.find_by id: token.payload['sub']
      return verified_user if verified_user

      reject_unauthorized_connection
    end
  end
end
```

If have any tip I will appreciate 👍

**Comment by aymericbouzy** [comment]
I'm doing something very similar, except I'm passing the `Authorization: Bearer <token>` header instead of passing the token in the parameters. 
It would be nice if Knock had an api method that could be used this way : 
```ruby
user = Knock.current_user request
```
that way all the complexity would be completely hidden away for the developer, and there would be full code reuse.

**Comment by brunowego** [comment]
Only need send with the URL the token.

**Comment by JerryArns** [comment]
@brunowego Did you still use this method? I am looking into doing the same.

**Comment by brunowego** [comment]
@JerryArns yep, for me works pretty well.

**Comment by JerryArns** [comment]
it doesnt work as token is just a string and token.payload['sub'] returns undefined method payload

**Comment by brunowego** [comment]
I am using Ember at frontend, I have tested Angular before, both works. 

Example of request:

```
Started GET "/cable?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE0OTczNTQ2OTksInN1YiI6ImE2OWFkMDAzLTdlMjYtNDg0ZC04NGYxLWFiNDFkZmY0ZDQxNiJ9.ilAecBjtEjI_1hgva_GEd9vbhOX74QwbgOhtXgQL-f4" for 127.0.0.1 at 2017-06-12 08:51:47 -0300
```

**Comment by mhluska** [comment]
How did you end up instructing Ember to send the token?
