### ISSUE TITLE
No support for full namespacing?

### ISSUE THREAD

**Issue by TheFlow0360** [nsarno/knock#150]
I tried to create all parts of my API namespaced, meaning nested modules `API::V1`. I also defined `authenticate_for` in my `API::V1::APIController` (derived from ApplicationController) like mentioned in the readme. However, whenever the TokenController is called, resolving the entity fails. The problem seems to be that `AuthTokenController` tries to deduce the entity name by truncating the `TokenController` from the class name and thus arrives at the entity name, without the corresponding namespace/module.

**Comment by estiens** [comment]
:+1:

**Comment by brunowego** [comment]
I have a project with Rails Engines and I have an engine for auth. To solve a similar issue, I just add the code below on token controller:

```rb
private

def entity_class
  ModuleName.const_get(entity_name).new
end
```

**Comment by TheFlow0360** [comment]
I refactored my namespaces, so I can'T try that, but I can imagine this will work. Thanks for the suggestion.
