### ISSUE TITLE
URL authentication 

### ISSUE THREAD

**Issue by gsdean** [nsarno/knock#17]
Would be nice be able to pass the token via query string. Something like

```
token = request.headers['Authorization'].split(' ').last || params[:token]
```

Interested?

**Comment by nsarno** [comment]
Using the request header is a best practice and passing the token through the query string is less secure. For that reason I think keeping Knock opinionated by default is a good thing.

On the other hand, I understand that you might need to use another way to pass the token. I'll consider adding a way to customize this behaviour.

Please let me know what your use case is for this, I'm interested.

Thank you for your feedback!

**Comment by gsdean** [comment]
The current use case is during development. Especially for an API, it's a lot easier to debug when you can authenticate via the URL. There are other use cases for JWT in the query string. Password reset links, invitation, etc.

In fact the standard even mentions it
`JSON Web Token (JWT) is a compact claims representation format intended for space constrained environments such as HTTP Authorization headers and URI query parameters.`

I'm not sure customization is necessary. Happy to create a PR too...

**Comment by nsarno** [comment]
Makes sense. Feel free to create a PR! With updated tests would be a must :)
