### ISSUE TITLE
Does knock work for traditional (not API-only) Rails applications?

### ISSUE THREAD

**Issue by anicholson44** [nsarno/knock#173]
I have a Rails 4 application with some API endpoints I want to secure. I see that knock is 'tailored for Rails API mode' but does that mean it won't work for applications not running in API mode?

Thanks!

**Comment by BigChief45** [comment]
I think it should work fine in non API mode applications. But you should then think carefully why you want or need to implement a JWT solution.

**Comment by hectorsq** [comment]
It is working for me. I am migrating a traditional Rails app from devise to knock, however I have to live with both authentication mechanisms for a while. My legacy AngularJS client apps use devise while my new Ember client apps use knock.

My legacy controllers inherit from ApplicationController which has the `before_filter :authenticate_user!` statement that fires devise authentication.

I created a new controller that inherits from ActionControllerBase and has the knock related statements. 

```
  class MedicalRecordController < ActionController::Base
    protect_from_forgery with: :null_session

    include Knock::Authenticable
    before_action :authenticate_user
    # Avoid conflict with devise
    undef_method :current_user
  end
```

It is important to undefine the `current_user` method to avoid conflicts with devise and strange behavior.

Then I inherit my controllers from this controller to avoid repeating the authentication code like this:

````
  class DocumentsController < MedicalRecordController
    def show
      document = Document.includes({groups: :observations}).find(params[:id])
      render jsonapi: document, include: "groups.observations"
    end
````

Hope this helps a little.
