### ISSUE TITLE
Role support

### ISSUE THREAD

**Issue by keitarobr** [nsarno/knock#176]
Hi, 

which would be the best approach to implement roles support with knock? Basically the user in my system can have multiple roles, while all being the same class (User).

**Comment by krsyoung** [comment]
Hey @keitarobr, I have roles in my application (User has an enum 'role').  I think it is independent of the authentication framework being used (knock just says they are who they say they are, not what they can do).

For the authorization aspect I'm using a gem called [pundit](https://github.com/elabs/pundit)

**Comment by alif-bae** [comment]
Hi @keitarobr i've had success in adding roles using [rolify](https://github.com/RolifyCommunity/rolify ) along with [pundit](https://github.com/elabs/pundit) on top (as @krsyoung mentioned) of it all to manage policies for specific roles and what not. Knock + Rolify + Pundit end up being a surprisingly well fitting authentication/authorization system.
