### ISSUE TITLE
Overlap with Warden

### ISSUE THREAD

**Issue by CharlesJQuarra** [nsarno/knock#18]
Hi,

I've noticed that this gem does not have warden as a dependency. I presume this is intentional? Is this gem reimplementing part of warden functionality?

I'm wondering what would it take to integrate knock as an authentication strategy into warden

**Comment by nsarno** [comment]
The JWT standard is really straightforward to implement and doesn't require a dependency such as warden.

I'm sure there already are JWT strategies for Warden but Knock does not aim to become this. Being simple to understand is one of Knock (and JWT) best feature in my opinion.
