### ISSUE TITLE
raise Knock.not_found_exception_class, not able to handle it

### ISSUE THREAD

**Issue by przbadu** [nsarno/knock#190]
I want to respond with `unauthorized` response for user not found or not a valid user and I have something like this:

```ruby
class ApplicationController < ActionController::API
  include Knock::Authenticable
  before_action :authenticate_user
  rescue_from Knock.not_found_exception_class, with: :unauthorized_access

  private

  def unauthorized_access
    render json: { global_errors: "Unauthorized!", status: :unauthorized  }
  end
end
```

But this never works, I am always getting 404 error without any content. I found knock:applicaiton controller is responding `head :not_found`, is that causing problem?

**Comment by mikestone14** [comment]
You should be able to define a method `unauthorized_entity` to handle the response:

```ruby
class ApplicationController < ActionController::API
  include Knock::Authenticable
  before_action :authenticate_user

  private

  def unauthorized_entity(_)
    render json: { global_errors: "Unauthorized!", status: :unauthorized  }
  end
end
```

**Comment by przbadu** [comment]
@mikestone14 but it still giving `404` and not json response:

```ruby
Processing by UserTokenController#create as */*                       
...
Completed 404 Not Found in 19ms (ActiveRecord: 0.9ms)
```

```ruby
class ApplicationController < ActionController::API
  include Knock::Authenticable
  before_action :authenticate_user

  private

  def unauthorized_entity(_)
    binding.pry
    render json: { global_errors: "Unauthorized!" }, status: :unauthorized
  end
end
```

I even put that debugger in that method and it is not triggering.

My Knock version is: `knock-2.1.1`

**Comment by zangab** [comment]
i did it like this and it works like a charm. 
`class UserTokenController < Knock::AuthTokenController
    private

    def authenticate
      unless entity.present? && entity.authenticate(auth_params[:password])
        raise Knock.not_found_exception_class
      end

      if entity.confirmed_at.nil?
        render json: { error: 'not_confirmed' }, status: 401
      end
    end
  end`

**Comment by filipemenezes** [comment]
```ruby
class UserTokenController < Knock::AuthTokenController
  skip_before_action :verify_authenticity_token, raise: false
  rescue_from Knock.not_found_exception_class, with: proc { head :unauthorized }
end
```
