### ISSUE TITLE
Certain routes in the same controller always return 401

### ISSUE THREAD

**Issue by GregTheGreek** [nsarno/knock#193]
I'm baffled.

I have three custom routes in the same controller, two of them work and one throws a 401 before I can even get to it. I'm using the same JWT token in my header. I can use that same token to access other routes that are protected. But for some reason, this controller won't allow my third route to work.

So I added another route to that controller... Still doesn't work.

Has anyone encountered this before?

**Comment by zangab** [comment]
how about some code? 😁
