### ISSUE TITLE
Time sensitive token

### ISSUE THREAD

**Issue by arjunmenon** [nsarno/knock#197]
Hey
Can you tell me the logic to add a expiry period for the tokens, like Facebook/Google Api's have?
This would be a good security feature.

**Comment by dnorthrupva** [comment]
Are you looking for something different than 
`  config.token_lifetime = 30.days`
within knock.rb?

**Comment by zangab** [comment]
@arjunmenon: no, knock does not provide this kinds of tokens. knock generates a token thats valid for a period of time (`config.token_lifetime`) and then its invalid -> user has to log in again.
if you need this kind of service, then [devise](https://github.com/plataformatec/devise) might be the thing you're looking for.

**Comment by andrerpbts** [comment]
Closing this issue since it seems to be answered in a good way and is already open for a long time :)
