### ISSUE TITLE
Syntax error during 'rails generate knock:install'

### ISSUE THREAD

**Issue by rixlabs** [nsarno/knock#22]
Hi,

executing :rails generate knock:install on my dev environment (Jruby 1.7.10 on Windows 7)

I got:
```
SyntaxError: C:/Ruby/jruby-1.7.10/lib/ruby/gems/shared/gems/knock-1.3.0/lib/knock.rb:12: syntax error,
 unexpected tLPAREN_ARG self.current_user_from_token = -> (claims) { User.find claims['sub'] }
```

I'm opening a pull request for removing the spaces that cause problem.
Let me know if is useful.

**Comment by nsarno** [comment]
I'd suggest updating to a version of JRuby (9.x) compatible with ruby 2.x

Apparently there's a syntax issue with lambda in older version of Ruby. Suppressing the parenthesis might be a better option for readability than removing the space.

[This article](http://ruby-journal.com/becareful-with-space-in-lambda-hash-rocket-syntax-between-ruby-1-dot-9-and-2-dot-0/) describes the issue.

**Comment by rixlabs** [comment]
I'am using 1.7.0 in ruby 2.0 mode: compat.version=2.0

Just made a test with 9000 and it's working.
Probably an old bug.
Unfortunately I must use 1.7.x cause of warbler


I make some tests with the paranthesis and let you know

btw. is better to specify min ruby version in the readme/doc

Thanks
Riccardo

**Comment by rixlabs** [comment]
Tested without parenthesis and it works.

Pull request already updated.

Up to you, let me know if you need some help also with the doc

**Comment by nsarno** [comment]
Compatibility issues should be fixed on a best effort as they are reported. If they can't be fixed, we'll update the documentation.

This one is pretty easy to fix so I see no reason not too. Those lambda will most likely go away in the v2 anyway :)

Thanks for the feedback
