### ISSUE TITLE
access current_user in model

### ISSUE THREAD

**Issue by JulienCorb** [nsarno/knock#229]
I am trying to setup authorization rules for my admin pages (Admin: [Rails Admin](https://github.com/sferik/rails_admin)), with [CanCanCan](https://github.com/CanCanCommunity/cancancan) on my rails API backend after I built an auth system with `knock` and `bcrypt`. 

the auth system works great and I can access `current_user` as expect in `/controllers/api/v1/users_controller.rb`. 

But CanCanCan works with a model/ability.rb file (see [here](https://github.com/sferik/rails_admin/wiki/Cancancan)) that calls this method to access to `current_user` (that I can override if needed) from the application controller: 

```
def current_ability
  @current_ability ||= Ability.new(current_user)
end 
```

my `model/ability.rb` is like so and should work as I am logged in with an admin user account:
```
class Ability
  include CanCan::Ability

  def initialize(user)
    if user && user.is_admin
      can :manage, :all
      can :access, :rails_admin # allow everyone to read everything
    end
  end
end
```

However I can't access `/admin` pages. It feels like `user` does not access `curent_user`

**Comment by nsarno** [comment]
This is lacking error details and doesn't look like an issue with the gem. Closing for now. Please feel free to re-open if you think there is indeed an issue with the gem.

**Comment by errawn** [comment]
> I am trying to setup authorization rules for my admin pages (Admin: [Rails Admin](https://github.com/sferik/rails_admin)), with [CanCanCan](https://github.com/CanCanCommunity/cancancan) on my rails API backend after I built an auth system with `knock` and `bcrypt`.
> 
> the auth system works great and I can access `current_user` as expect in `/controllers/api/v1/users_controller.rb`.
> 
> But CanCanCan works with a model/ability.rb file (see [here](https://github.com/sferik/rails_admin/wiki/Cancancan)) that calls this method to access to `current_user` (that I can override if needed) from the application controller:
> 
> ```
> def current_ability
>   @current_ability ||= Ability.new(current_user)
> end 
> ```
> 
> my `model/ability.rb` is like so and should work as I am logged in with an admin user account:
> 
> ```
> class Ability
>   include CanCan::Ability
> 
>   def initialize(user)
>     if user && user.is_admin
>       can :manage, :all
>       can :access, :rails_admin # allow everyone to read everything
>     end
>   end
> end
> ```
> 
> However I can't access `/admin` pages. It feels like `user` does not access `curent_user`

Hi! have you figured this out? I'm also facing this. CanCanCan cannot access current_user from knock

**Comment by errawn** [comment]
> > I am trying to setup authorization rules for my admin pages (Admin: [Rails Admin](https://github.com/sferik/rails_admin)), with [CanCanCan](https://github.com/CanCanCommunity/cancancan) on my rails API backend after I built an auth system with `knock` and `bcrypt`.
> > the auth system works great and I can access `current_user` as expect in `/controllers/api/v1/users_controller.rb`.
> > But CanCanCan works with a model/ability.rb file (see [here](https://github.com/sferik/rails_admin/wiki/Cancancan)) that calls this method to access to `current_user` (that I can override if needed) from the application controller:
> > ```
> > def current_ability
> >   @current_ability ||= Ability.new(current_user)
> > end 
> > ```
> > 
> > 
> > my `model/ability.rb` is like so and should work as I am logged in with an admin user account:
> > ```
> > class Ability
> >   include CanCan::Ability
> > 
> >   def initialize(user)
> >     if user && user.is_admin
> >       can :manage, :all
> >       can :access, :rails_admin # allow everyone to read everything
> >     end
> >   end
> > end
> > ```
> > 
> > 
> > However I can't access `/admin` pages. It feels like `user` does not access `curent_user`
> 
> Hi! have you figured this out? I'm also facing this. CanCanCan cannot access current_user from knock

Hi! @JulienCorb and future readers!
I made it work by including `  include Knock::Authenticable` and changing the parameter of initialize method from user to current_user

please see working code below:

**app/models/ability.rb**
```
class Ability
  include CanCan::Ability

  def initialize(user)
    if user && user.is_admin
      can :manage, :all
      can :access, :rails_admin # allow everyone to read everything
    end
  end
end
```

**app/controllers/application_controller.rb**
```
class ApplicationController < ActionController::API
  include Knock::Authenticable

  rescue_from CanCan::AccessDenied do |exception|
    render json: { error: 'You are not authorized to perfom this action' }, status: :forbidden
  end
end

```

**Result:**
![image](https://user-images.githubusercontent.com/18679035/87853390-238ec000-c93c-11ea-8e21-2d7e3198a512.png)

Thanks! ✨
