### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by jalberto** [nsarno/knock#237]
I love the simplicity of this gem, but is getting outdated related to JWT and Rails itself.
There are some small PRs that will mitigate this.

**Comment by nickhall** [comment]
> Is this gem going to be maintained?
>
> Yes.

Oh...

**Comment by jalberto** [comment]
then maybe @nsarno is having some issues or requires help?

**Comment by nsarno** [comment]
@nickhall every time I arrive on this page, I stare at this line for 30s and consider committing to erase it then just proceed to back away slowly and pretend it doesn't exist for the next 3 months. Excuse my foolishness, I was young and pretentious. But feel free to fork of course...

>  then maybe @nsarno is having some issues or requires help?

@jalberto Thank you. I would be more than happy to onboard and add as a collaborator people willing to help! Let me know if that's you and I'll reach out to you directly outside of this issue.

**Comment by nickhall** [comment]
Forgive my snarkiness. There are a number of pull requests that have gone unanswered so I assumed the worst. If you really do just need help I'd be glad to take a look as well!

**Comment by jalberto** [comment]
@nsarno I am willing to help :)
I don't promise to be able to dedicate lot of time, but enough to review some PRs and help to keep this nice lib alive :)

**Comment by bjensen** [comment]
So what is the alternative? Currently Im using just the jwt gem with auth0 but rspec request specs seam to be a bit of a pain..

**Comment by jalberto** [comment]
I plan to begin some review work and updates as soon my current work peak
is back to normal.

Meanwhile feel free to use PRs to address your issues.

**Comment by sshaw** [comment]
@jalberto would be good to do a release with [this fix](https://github.com/nsarno/knock/commit/26c9090abc11b0eecc369d4c8f89f90c10f3ae33). Work is already done. 

This caused some problems for me today, i.e., the authentication was failing because an error related to a bug in the code was being swallowed.  😿

**Comment by kwent** [comment]
@jalberto please give us some news and try to find a new maintainer 🙏🙏
