### ISSUE TITLE
Support rails 6 autoload zeitwerk

### ISSUE THREAD

**Issue by ShakeJ** [nsarno/knock#240]
Rails 6 default auto loader is 'zeitwerk', 
<img width="1038" alt="스크린샷 2019-06-02 오후 10 50 48" src="https://user-images.githubusercontent.com/4054312/58762217-e5440f00-8588-11e9-8fe3-4fc4e0ababea.png">

This method requires that the file name be exactly in the class name, but is there a support policy for that method?

**Comment by FunkyloverOne** [comment]
Hey @ShakeJ, why did you close an issue?

**Comment by ShakeJ** [comment]
@FunkyloverOne Hi :) I used knock gem! 
My project upgrade rails 6.0, and some problem happend.
rails 6.0 changed default autoloader is classic to zeitwerk. 
but knock gem is not acceptable autoloader(zeitwerk).

Please check this discussion : https://github.com/rails/rails/issues/36381 
Thanks.

**Comment by johnknapp** [comment]
The solution outlined in the discussion mentioned above did not solve the ActionController::InvalidAuthenticityToken in rails 6.0.0.rc2

**Comment by Mayurifag** [comment]
Any work on this?

**Comment by ShakeJ** [comment]
thanks :)

**Comment by tisba** [comment]
How did you solve this issue, @ShakeJ?

**Comment by nsarno** [comment]
The issue should be fixed once #248 is merged.
