### ISSUE TITLE
Knock not returning token on user sign up

### ISSUE THREAD

**Issue by akinsikuoluwafemi** [nsarno/knock#271]
I noticed that knock gem doesn't send a token when a user signs up, it only does on user login, is there a workaround for this?.

**Comment by chrisgeek** [comment]
@akinsikuoluwafemi User signup does not automatically include authentication, I believe this gem is meant to authenticate users trying to login rather than sign up. If what you want is to authenticate after signup, then you can post your create action code and we could take a look. cheers !

**Comment by akinsikuoluwafemi** [comment]
Okay, thanks a lot @chrisgeek
