### ISSUE TITLE
Make unmaintained state better visible?

### ISSUE THREAD

**Issue by tisba** [nsarno/knock#273]
I was about to ask for a new release when I saw the [latest commit](https://github.com/nsarno/knock/commit/eec6af436afce46a65264ce9766cad6aad3d05dc) about knock not being maintained.

Can I suggest to make this a H1 right on top of the Readme, so that it is better visible? It is a bit hidden in the text IMO.

Also, @nsarno, you could archive the project in addition to make it even easier to spot that this is no longer maintained.

Anyhow: Thank you @nsarno for your work all this time 👏 🙇

**Comment by nsarno** [comment]
Thanks for the kind words and suggestions.
