### ISSUE TITLE
Readme inconsistent with 1.4.0?

### ISSUE THREAD

**Issue by duboff** [nsarno/knock#32]
I updated to 1.4.0 and everything stopped working. I assume there are some changes I need to make but on the readme the setup is exactly the same. Any chance for explaining what has changed?

**Comment by jkamzi** [comment]
If you upgraded from 1.3 then you should note the following changes:

___1.3___
```POST /knock/auth_token { email: 'foo@example.net', password: 'bar' }```
___1.4___
```1.4 POST /knock/auth_token {"auth": {"email": "foo@bar.com", "password": "secret"}}```

Note how 1.4 wrap the credentials in "auth"

**Comment by duboff** [comment]
I am actually using knock with Auth0, so don't hit the endpoint manually. I use Knock::Authenticable as per the readme.

Where I think the regression comes in is the recommended audience verification in the initializer is no longer compatible with the rest of the code: https://github.com/nsarno/knock/blob/master/lib/generators/templates/knock.rb#L58

Basically, the generated initializer suggests using a lambda but the code expects a value. I will try to submit a PR to bring those in line.

**Comment by duboff** [comment]
Added a PR in #33

**Comment by nsarno** [comment]
1.4.1 should fix this. Thanks @duboff :+1:
