### ISSUE TITLE
[Question] How do I authenticate an Auth0 user in my request specs?

### ISSUE THREAD

**Issue by feliksg** [nsarno/knock#35]
I'm trying to write some request specs for my API but the following code results in a 401 status:

```ruby
# spec/support/auth0.rb

def authenticate(user)
  # user.auth0_id contains the actual user id from Auth0
  Knock::AuthToken.new(payload: { sub: user.auth0_id }).token
end
```

```ruby
# spec/requests/dashboard_spec.rb

require "rails_helper"

RSpec.describe 'GET /dashboard' do
  let(:user) { create(:user) }
  let(:auth_token) { authenticate(user) }

  context 'when a user is logged in' do
    it "returns a 200 response" do
      get '/dashboard', headers: { 'Authorization' => "Bearer #{auth_token}" }
      expect(response.status).to eq 200
    end
  end
end
```

Any idea on how to resolve this? By the way, i'm using the v2 branch with my updates found [here](https://github.com/feliksg/knock/tree/migrate-fixes-from-master)

**Comment by nsarno** [comment]
This is the way I describe in the Readme:

```ruby
request.env['HTTP_AUTHORIZATION'] = "Bearer #{token}"
```

Let me know if it works for you. Thank you for trying the v2 :+1:

**Comment by nsarno** [comment]
I assume I can close this. Feel free to reopen if you have any more trouble with this.
