### ISSUE TITLE
Document change in header-passed token representation in CHANGELOG

### ISSUE THREAD

**Issue by yawn** [nsarno/knock#36]
Commit 18b2cfb102a0f0514685ac4dce5a7d27f6fd23c2 now *requires* prefixing a header-passed token with a `Bearer ` string. The previous release supported both forms, with and without the prefix. This breaks compatibility with all users who did *not* use prefixed tokens.

Please document this change in the `CHANGELOG` and / or consider changing the regular expression to accommodate the old behaviour.

**Comment by nsarno** [comment]
Thank you for reporting this. Introducing a breaking change is not something that should have happened and I should have payed more attention to the consequences of this change at the time. I don't think being so strict on the parsing of the prefix makes sense either.

I'm leaning towards reverting to the previous solution using `split.last`, although I'm open to suggestions on how this header should be parsed if there is a better way.

**Comment by yawn** [comment]
#37 is a good solution. If you want to capture the intent better than using a simple call to `split`, you might want to use

* the terminology outlined in [RFC 7235](https://tools.ietf.org/html/rfc7235#section-4.2) which defines `Basic`, `Bearer` etc. as "auth-scheme" 
* the value of the "auth-scheme" is a "token" from [RFC 7230](https://tools.ietf.org/html/rfc7230#section-3.2.6)

Loosely applied this could result in a regexp like this:

```
((?<auth-scheme>[!|#|$|%|&|'|*|+|-|.|^|_|`|\||~|[:graph:]]+)?(?: ))?(?<token>.+)
```

This does not capture the format of the token but the appropriate normalizations would (one would assume) be handled by the underlying web server (or related infrastructure) in any case. Currently your code does not expose the scheme, but this might be worthwhile at some later point.

**Comment by nsarno** [comment]
I agree we should aim towards a solution based on the RFC. I will still go with #37 for the moment as the goal is primarily to fix the breaking change.

Really appreciate the help, thank you :+1:

**Comment by yawn** [comment]
You are welcome.
