### ISSUE TITLE
undefined method `length' for nil:NilClass while running specs

### ISSUE THREAD

**Issue by suezzo** [nsarno/knock#45]
Hello,
I try to authenticate user in my tests. So far my spec looks like:

```
require 'rails_helper'

RSpec.describe 'GET /posts' do
  subject { response }

  let(:user) { create(:user) }
  
  it 'authenticate user' do
    authenticate
    get '/posts'
    expect(response.status).to eq 200
  end
end
```

My User model has `auth_id` column which stores auth0 user id. My code method is below.

```
def authenticate
  token = Knock::AuthToken.new(payload: { sub: user.auth_id }).token
  request.env['HTTP_AUTHORIZATION'] = "Bearer #{token}"
end
```

Every time I run spec I receive error about undefined method `length`.

```
Failure/Error: authenticate
  NoMethodError:
    undefined method `length' for nil:NilClass
```

I will really appreciate it if someone can suggest me what's wrong with my code.

Thanks!

**Comment by suezzo** [comment]
I've found that this line is causing the error

`secret += '=' * (4 - secret.length.modulo(4))`

I'm not sure why, because my `config.token_secret_signature_key` looks like

```
config.token_secret_signature_key = -> {
  secret = Rails.application.secrets.auth0_client_secret
  secret += '=' * (4 - secret.length.modulo(4))
  Base64.decode64(secret.tr('-_', '+/'))
}
```

Also I'm able to retrieve `auth0_client_secret` from console, the same is with generating new AuthToken.

**Comment by nsarno** [comment]
It seems like `Rails.application.secrets.auth0_client_secret` is not defined when you create the lambda. I'm just guessing as I don't have the entire code under my eyes.
