### ISSUE TITLE
Knock::AuthTokenController extending

### ISSUE THREAD

**Issue by iLikeKoffee** [nsarno/knock#47]
Hello. In some cases AuthTokenController may need custom behaviour, but all the methods inside except `create` action are `private`. What about making them `protected`? This will allow users add some custom logic. For example, adding expiration date or user identifier to response and etc

**Comment by iLikeKoffee** [comment]
Added PR #48 for this issue.

**Comment by nsarno** [comment]
It should definitely be possible to achieve this by modifying the controller rather than relying on configuration. I'll have a look at merging your PR or coming with another solution whenever I can.

Thanks a lot for contributing and apologies for the late reply! :+1:

**Comment by iLikeKoffee** [comment]
@nsarno No problem! Now, I achieve this customization by the entire Knock::AuthController to my project. It looks like this: 

```
class AuthTokenController
  before_action :authenticate!

  def create
    user = find_user
    render json: {jwt: auth_token(user).token, user: user}, status: :created
  end

  # Private methods copied from Knock::AuthController.
  # This is is a workaround because those methods in Knock::AuthTokenController are private.
  # I hope this will be removed when my PR (https://github.com/nsarno/knock/pull/48) merged.

  private

  def authenticate!
    raise ActiveRecord::RecordNotFound unless user.authenticate(auth_params[:password])
  end

  def auth_token(user)
    Knock::AuthToken.new payload: {sub: user.id}
  end

  def find_user
    Knock.current_user_from_handle.call auth_params[Knock.handle_attr]
  end

  def auth_params
    params.require(:auth).permit Knock.handle_attr, :password
  end
end
```
It works, but It's not the most beautiful solution.
Instead, i want It look like this:
```
class AuthTokenController < Knock::AuthTokenController
  before_action :authenticate!

  def create
    user = find_user
    render json: {jwt: auth_token(user).token, user: user}, status: :created
  end
end
```

Thanks in advance!

**Comment by nsarno** [comment]
Closing this. Cf #48 and #72.

**Comment by danhixon** [comment]
#72 allows us to customize the JWT payload but I'd like to be able to do what @iLikeKoffee is doing here: providing a token and the user json. Is there a way to do that without copying and pasting the private methods into a custom controller?  Perhaps a single protected method like the following:

```
  #... excerpt from auth_token_controller.rb
  def create
      render json: json_payload, status: :created
  end

  protected
  def json_payload
    auth_token
  end

  private
  #... the rest of the file
```

All the private methods are in tact and if a user desires he/she can override the json_payload method like so:

```
class UserTokenController < Knock::AuthTokenController
  protected
  def json_payload
    { token: auth_token, user: entity }
  end
end
```

I'd be happy to submit a PR if desired. Or let me know if there is already a way to achieve what I'm hoping for.
