### ISSUE TITLE
permanent tokens?

### ISSUE THREAD

**Issue by johnrees** [nsarno/knock#49]
Is there a recommended method for generating permanent tokens?

I ask because I'm making both a mobile app and the Rails API it will use, and I only want the user to login once, after they install the app.

I noticed the default expiration period is `config.token_lifetime = 1.day` with no obvious way to set this to infinity/nil. And after a cursory search I didn't see any mention of refresh tokens.

For now I've set it to an arbitrary long-term future date, `10.years`. And will store the token locally in the app, but is that a bad idea? Thanks

**Comment by nsarno** [comment]
The expiration claim is optional (https://tools.ietf.org/html/rfc7519#section-4.1.4). So not specifying it is the way to go.

Which makes me realize that we're forcing its use in knock by always specifying the claim. I'll make sure this get fixed.

Thank you for bringing this up :+1:

**Comment by nsarno** [comment]
This is now available on master since #63 was merged. It will be in the next release.

Thank you for your patience!

**Comment by renemendoza** [comment]
Is it possible to have both types of tokens? E.a. give some users permanent tokens and give some other users regular valid only for 24 hours tokens?

**Comment by suyesh** [comment]
I have one stupid question. Will i be able to signout and still be able to use the same token later if i set the lifetime to nil?
