### ISSUE TITLE
Support for Rails 4.0.x ?

### ISSUE THREAD

**Issue by ZiaMM** [nsarno/knock#50]
When I run bundle update I get:
In Gemfile:
    rails (= 4.0.13)
    knock was resolved to 1.0.0, which depends on
      rails (~> 4.2)
I tried to force a lower version of knock, but this was "not found."

Going to the next version of Rails has many code-breaking changes within this app.
Is there a way to run knock on Rails 4.0.x ?

**Comment by nsarno** [comment]
I don't think there is a good reason for knock not being compatible with rails >= 4.0. I'll have a look into this whenever possible.

Thanks for the feedback and sorry about the late reply :+1:

**Comment by ZiaMM** [comment]
I wrote my own solution using only the 'jwt' gem.  But in my experiments, there was an issue finding some of the controller and other methods provided by the Gem's code - copying these into the app solved that.  Also, one needs to install the 'rails-secrets' gem (needed for jwt).
