### ISSUE TITLE
Adding custom message when RecordNotFound exceptions occurs

### ISSUE THREAD

**Issue by SORRROW** [nsarno/knock#52]
Hey, I see you specify for us to raise an ActiveRecord::RecordNotFound for the authentication process but I am having trouble doing so as I do not know where to do it since the controller for generating tokens based on user credentials is the one you provide with your gem.

What I would like to do is send back with the status a response with a custom message like "Wrong Credentials" for example when such exception occurs. I imagine I should use a rescue but I do not know how or where, thanks.

**Comment by nsarno** [comment]
I'm not sure I understand exactly what you are saying by "you specify for us to raise an ActiveRecord::RecordNotFound for the authentication process".

Do you mean inside `config.current_user_from_handle` or `config.current_user_from_token`?

**Comment by SORRROW** [comment]
Well for both actually, I'd like to be able to send a message along the request when the token is wrong or the user credentials are incorrect.

**Comment by nsarno** [comment]
Makes sense. I'll try to provide a solution for this.

**Comment by SORRROW** [comment]
Okay thanks, looking forward to it.

**Comment by gustavovnicius** [comment]
Wouldn't be a lovely design if the authenticate raises an Knock related exception then if you need to have some custom method you catch it on your ApplicationController (or any controller like that) with [rescue_from](http://api.rubyonrails.org/classes/ActiveSupport/Rescuable/ClassMethods.html#method-i-rescue_from)?

**Comment by nsarno** [comment]
I believe this is solved by https://github.com/nsarno/knock/pull/80
