### ISSUE TITLE
`current_user` name collision

### ISSUE THREAD

**Issue by toby-1-kenobi** [nsarno/knock#53]
Using Knock I added token-based authentication to a rails app that already had session-based authentication. There was already a `current_user` method that was included in ApplicationController which looked in the session for the logged in user. This method prevented Knock authentication working because Knock checks if it can get a result from `current_user` to see if the user is authenticated, but it would call my `current_user` method instead of it's own.

To work around this I had to change the name of my `current_user` method to something else.

This sort of collision should be prevented using namespaces or something like that. At the very least it should be clearly documented that you can't have your own `current_user` method in controllers using Knock. It would have saved me a lot of debugging time.

**Comment by nsarno** [comment]
I believe the readme is pretty clear about adding a `current_user` method to your controller, if you include the `Knock::Authenticable` module. I you feel differently, feel free to create a PR to suggest improvements.

You can't prevent method name collision with namespaces when including modules. If you think of a good solution to this, PR are always welcome.

As a possible solution, I would suggest that you avoid mixing multiple authentication system in the same controller as it is likely to create confusion.

It's hard for me to give a better answer without seeing the code.

**Comment by toby-1-kenobi** [comment]
I had a closer look and can see now that namespaces can't be of any help here.

The reason I have multiple authentication systems in one controller is because I have already set up session-based authentication for users interacting with the app through their browsers, now I'm making an offline version as an android app that duplicates some of the interface functionality, then authenticates with the app when it has a connection to sync data. For that I felt that token-based authentication would be best.

Anyway, my work around of changing the method name for the sessions helper is fine. I've put in a PR with a suggestion for making the docs a little clearer about that.

**Comment by nsarno** [comment]
Thanks for the feedback and the PR 👍 

I definitely see why you would need both authentication system in your app, although I would still recommend that you use them in different controllers by creating a specific API endpoint for example.
