### ISSUE TITLE
Adding private claims to the token

### ISSUE THREAD

**Issue by pietschy** [nsarno/knock#56]
Hi there, just wondering if you thoughts on adding additional claims to the token payload. I'd like to add some additional user information to it but it looks like I'd have to subclass the AuthTokenController (which will be easier once #47 is fixed).

Thanks and cheers

**Comment by nsarno** [comment]
Definitively on my list of things to improve in priority 👍 Hoping to tackle this in a near future.

**Comment by pietschy** [comment]
Cool, thanks @nsarno.

**Comment by nsarno** [comment]
This will be possible once #72 is merged. The payload is now created via serialization of the entity model (E.g. `User`) by implementing `to_token_payload`.
