### ISSUE TITLE
Does it support Mongoid ?

### ISSUE THREAD

**Issue by belguzman** [nsarno/knock#57]

**Comment by nsarno** [comment]
I don't think there's anything that would prevent you from using `Mongoid`.

Although you might need to configure the following differently in the initializer:

```ruby
self.current_user_from_handle = -> handle { User.find_by! Knock.handle_attr => handle }
self.current_user_from_token = -> claims { User.find claims['sub'] }
```

At the moment, it's also a requirement for these lambdas to raise an `ActiveRecord::RecordNotFound` exception when the user can't be found. Admittedly this shouldn't be the case and I plan to remove this.

If you end up using knock with mongoid, it would be great if you could let me know how you go and update this issue with your solution! 👍

**Comment by belguzman** [comment]
Will do, thanks @nsarno

**Comment by michaelunltd** [comment]
@nsarno We're using knock with mongoid. It still does raising `ActiveRecord::RecordNotFound`, i worked it around by overriding `authenticate` private method in `Knock::AuthTokenController` and raise a custom exception.

eg.

```
  def authenticate
    unless entity.present? && entity.authenticate(auth_params[:password])
      raise ExceptionHandler::InvalidPassword, "Invalid password"
    end
  end
```

**Comment by frontandstart** [comment]
@michaelunltd 
I just read it and have idea to make it configurable but it already done
if you check last line of default knock initializer you will see this: 
![screen shot 2018-08-29 at 4 07 07 pm](https://user-images.githubusercontent.com/8098344/44789642-c0f47580-aba5-11e8-950c-2b1e78960cd0.png)
And set [Mongoid::Errors::DocumentNotFound](https://www.rubydoc.info/github/mongoid/mongoid/Mongoid/Errors/DocumentNotFound)
```ruby
Knock.setup do |config|
  ...
  config.not_found_exception_class_name = 'Mongoid::Errors::DocumentNotFound'
  ...
end
```
