### ISSUE TITLE
Token verification fail

### ISSUE THREAD

**Issue by yordis** [nsarno/knock#6]
I just download this example from Auth0 https://github.com/auth0/auth0-rubyonrailsapi-sample and for some reason if you pass **verify=true** it fail.

I traced it down to this line https://github.com/nsarno/knock/blob/master/app/model/knock/auth_token.rb#L9 so after that the problem is JWT gem but it works with that flag in false but at the same time that have to be true :smile:

**Comment by nsarno** [comment]
Could you provide a failing test so I can reproduce the issue? Thanks

**Comment by yordis** [comment]
```
Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2NhcmliYmVhbnBpcmF0ZXNzdHVkaW8uYXV0aDAuY29tLyIsInN1YiI6InR3aXR0ZXJ8MTMwMDE5MTY0MiIsImF1ZCI6Ik1pUGZiNThyNnNQVzFFSEtXdXl2MWlMNjBUdVloeVFFIiwiZXhwIjoxNDQxNDEzNTUwLCJpYXQiOjE0NDEzNzc1NTB9.C2ADZ5sv18pEV9A3KeG9mGknwFHdtOOAQyTaYD9G-ws
```

```
Secret: qMPu175nNxLQSeannJZLtDz8NferbnL3tJ0hGKeRDEITtkquTDfVjF7xTbgNzHTq
```

**Comment by nsarno** [comment]
The example you linked is not using the Knock gem.

This is the correct sample application from Auth0 using the Knock gem:

[auth0-ruby-samples/ruby-on-rails-api](https://github.com/auth0/auth0-ruby-samples/tree/master/ruby-on-rails-api)

Is this the one you are talking about?

If so, can you provide a failing test that I can run to reproduce the issue. Something that looks like the `test/secured_ping_controller_test.rb` of the sample app and that I could run like this:

`rake TEST=test/failing_test.rb`

That would be really helpful. Thanks

**Comment by yordis** [comment]
@nsarno is the other example but for some reason was something related to postman

thanks for your help.
