### ISSUE TITLE
Authentication for a scoped user?

### ISSUE THREAD

**Issue by pixelblend** [nsarno/knock#60]
I would like to use Knock for an API that allows the reuse of an email address against multiple different accounts. Just like Slack, the account would be determined by the subdomain that the user logs in from.

Is it possible to scope the `current_user` to be found via an associated `Account` object?

e.g. `Users.where(account_id: $account_id).find_by! Knock.handle_attr => handle`

**Comment by nsarno** [comment]
I don't think it's possible at the moment, at least not in a nice way. Making this possible might be as easy as passing the request through to the current_user retrieval lambda. I'll think about a good way to implement this.

This is an interesting use case, thanks for the feedback 👍

**Comment by pixelblend** [comment]
That would be amazing, thanks for considering it.

**Comment by nsarno** [comment]
This will be fixed once #72 is merged. The entire request is passed down from the controller to `User.find_for_token_creation`.

**Comment by pixelblend** [comment]
I've been able to implement the changes to the authentication, exactly as I'd described.

This is fantastic, thanks for all your hard work!
