### ISSUE TITLE
Rails cannot recognise the engine version

### ISSUE THREAD

**Issue by mihaibb** [nsarno/knock#67]
Versions of rails and rails-api:
```
gem 'rails-api', '0.4.0'
gem 'rails', '~> 4.2.3'
```

Specs written with rspec get in some kind of conflict and throws the error that it cannot find the version of the engine version.
The path provided in the error is the same as the version file but somehow it cannot be loaded.

**Comment by nsarno** [comment]
Could you provide the exact error message as well as a way to reproduce it. Thanks!

**Comment by nsarno** [comment]
Feel free to reopen with more details if you still have an issue.
