### ISSUE TITLE
Add an action to check if token is valid

### ISSUE THREAD

**Issue by AmrN** [nsarno/knock#69]
I think  it would be nice to have an additional action alongside `AuthToken#create` (maybe `AuthToken#validate`) that simply returns success if the provided token is valid.

It can be useful when the client just wants to check if the token is valid and hasn't expired without having to decode it.

**Comment by nsarno** [comment]
Calling any authenticated endpoint will provide the same result with one less HTTP request if the token isn't expired. If you want a special endpoint for this, you can implement it inside your app but I don't think it needs to be part of this gem.

Thanks for the feedback and feel free to let me know if you think I'm missing something 👍
