### ISSUE TITLE
No method error: User doesn't have 'authenticate'

### ISSUE THREAD

**Issue by brandonpittman** [nsarno/knock#7]
Knock looks like a great solution but I'm having issues. I know Knock is in there. The routes are registered and when I hit a secured page with no headers supplied, I get a 401. However, when I do supply the correct headers, I get this no method error. Any ideas what's up?

https://github.com/brandonpittman/knock_test/blob/master/app/controllers/users_controller.rb

Has anyone done a tutorial using Knock that you know of? I'm not having a lot of luck getting it up and running.

**Comment by nsarno** [comment]
Add the `bcrypt` gem to your Gemfile (it's usually present but commented by default), and use [has_secure_password](http://api.rubyonrails.org/classes/ActiveModel/SecurePassword/ClassMethods.html#method-i-has_secure_password) in your User model.

```ruby
# Schema: User(name:string, password_digest:string)
class User < ActiveRecord::Base
  has_secure_password
end
```

Alternatively you could provide your own `authenticate` method that takes the user password in argument and returns a boolean.

This was not mentioned in the README and it definitely should. Thank you for your feedback!

**Comment by brandonpittman** [comment]
Thanks for responding. I was thinking I was going crazy and missed something.
