### ISSUE TITLE
Revoking a token

### ISSUE THREAD

**Issue by balakarthik2011** [nsarno/knock#71]
I need to know how to handle the logout operation, because the token will be valid up to the time mentioned in the expiry claim, but if a user log out from the application before the expiry time, the token should become invalid.
I was searching the way to revoke a jwt, i found some of the solutions [here](http://stackoverflow.com/questions/28759590/best-practices-to-invalidate-jwt-while-changing-passwords-and-logout-in-node-js) where someone said to use blacklisting mechanism and use of refresh token, i need to know whether these features are implemented in the knock or any other alternatives for invalidating a JWT.

**Comment by nsarno** [comment]
In a common scenario, the user simply deletes the token on the client, no request to the server is required.

A few things to keep in mind:
- Each token should have a relatively short expiration time to limit impact of compromised tokens.
- The credentials must be requested every time for critical operations. e.g. changing the password (this is valid for any kind of authentication)

The only case where this is potentially an issue is when you want to implement a "force logout on behalf of the user" feature. Although I believe this is very rarely really required.

I don't recommend implementing blacklisting as this means losing the "statelessness" that comes with using JWT.

This was previously discussed in [this issue](https://github.com/nsarno/knock/issues/15), where a solution for this was suggested.

Hope that helps!
