### ISSUE TITLE
Authorization header works with any random JWT prefix

### ISSUE THREAD

**Issue by chewedon** [nsarno/knock#73]
Awesome gem.

I followed Adam's JWT tutorial in the past: http://adamalbrecht.com/2015/07/20/authentication-using-json-web-tokens-using-rails-and-react/ which builds a JWT from scratch without using gems.

Today, I tried this library, works like a gem (pun intended).

I have one issue though, hopefully it hasn't been asked before.

When I use cURL or Postman to make the request:

![screen shot 2016-05-22 at 5 34 00 pm](https://cloud.githubusercontent.com/assets/1171355/15453303/723286fc-2043-11e6-8fec-87c21c47aaa8.png)

It doesn't matter whether I put in the HTTP Headers:

    "Authorization: JWT <the_real_JWT_here>"

Or

    "Authorization: Blah <the_real_JWT_here>"

The Rails server still lets it through....is this how it's suppose to work?

For example, this Github README uses `Bearer <JWT_token>`. I would have thought a real JWT should enforce the Authorization header to have the word "JWT" instead of letting anything there.

Any ideas?

**Comment by chewedon** [comment]
Okay, after reading the official JWT page: https://jwt.io/introduction/

They themselves use `Authorization: Bearer <jwt>`. So I am wrong in the part where I said it should be `Authorization: JWT <jwt>`.

I had always though the prefix before the JWT was required...or at least important...I'm beginning to question the purpose of the prefix.

**Comment by nsarno** [comment]
I confirm the prefix is entirely ignored in the current implementation.

Here's the code parsing the header: `request.headers['Authorization'].split.last`.

Although I do understand how the prefix could be used, I've never been in a situation myself where I cared about it so much. The "Bearer" prefix is a generally accepted default value, not something really meaningful I believe.

I'm closing this as you perfectly answered yourself. If you think there would be value in being able to specify a prefix and enforcing it, feel free to reopen the issue and discuss it here.

Thanks for all the feedback! 👍
