### ISSUE TITLE
404 response when credentials are bad

### ISSUE THREAD

**Issue by toby-1-kenobi** [nsarno/knock#76]
When a client tries to authenticate with bad credentials the server response is 404. The client then wont know if the credentials are bad or the sever is offline. Perhaps a 401 or 403 response would be better.

**Comment by toby-1-kenobi** [comment]
Perhaps it should be configurable in Knock.setup

**Comment by nsarno** [comment]
> This is a security best practice to avoid confirming the existence of a user when bad credentials are provided. The 404 in this case means we did not find a user matching the given credentials.

https://github.com/nsarno/knock/issues/44

There's always a bit of debate going on between which of 401, 403 or 404 is more appropriate. Although they're all perfectly valid options, knock is using 404 for the reason given above.

Also if the server is down / offline, I do not believe the answer would be or should be 404. As for being configurable, I'm not against it but I don't think it's absolutely necessary. Happy to hear your thoughts if you think it is.
