### ISSUE TITLE
Support for Rails 5 RCs

### ISSUE THREAD

**Issue by pjkelly** [nsarno/knock#77]
Any recommendation on using Knock with the Rails 5 release candidates?  Right now, the dependency is based on official releases (per PR #30).  In the meantime, I've forked this repo and adjusted the dependency accordingly but wanted to know if you're planning an official release of Knock that supports the release candidates or not.

**Comment by pjkelly** [comment]
I should also add that if you're interested in a pull request, I'm happy to submit one.

**Comment by nsarno** [comment]
The dependency is `>= 4.2` so you should be able to use it with Rails 5 without changing anything. Do you get an error when trying to do this?

**Comment by pjkelly** [comment]
Yeah, in order to accept prerelease gems, apparently you need to have a prerelease as your minimum dependency as well, e.g. `>= 4.2.0.rc3`.  Since Rails 5 _should be_ out of release candidate soon, it might not be worth pushing a release just for this - just thought I'd bring it to your attention though.

http://guides.rubygems.org/patterns/#prerelease-gems

**Comment by nsarno** [comment]
Right, I imagine I had to do the same when I tried with the beta. Like you said, not worth a release though.

If you want you can submit a PR, it won't be merged but it can be useful as reference for other people trying to do the same.

Thanks for the feedback!
