### ISSUE TITLE
Namespacing models

### ISSUE THREAD

**Issue by ekampp** [nsarno/knock#79]
Hi there. 

I'm trying to implement  Knock in a Rails 5 API, where I have everything namespaced (e.g. V1::User, V1::UsersController, etc..).

When mounting the knock authentication endpoint inside the namespace, like this, it works fine for exchanging username and password for a JWT:

```ruby
  constraints format: :json, defaults: { format: :json } do
    namespace :v1 do
      post :user_token, to: 'user_token#create'
      resources :rooms
    end
  end
```

It doesn't work to go to the rooms endpoint afterwords, using the new JWT token. I get this exception: `NameError: uninitialized constant User`. This is because I have this in my V1::BaseController:

```ruby
before_action :authenticate_user
```

[Here](https://github.com/nsarno/knock/blob/master/lib/knock/authenticable.rb#L34-L37) this is being constantized into the User model, so it's clear that a namespace is missing. 

I then tried adding this to my controller instead:

```ruby
before_action :authenticate_v1_user
```

But this gets transformed into a `V1User` class, not as expected a `V1::User`. 

Is there a way that I'm not seeing for easily letting Knock know that I'm trying to get at a namespaced user? 

Thanks in advance,
Emil

**Comment by nsarno** [comment]
Thanks for the detailed feedback. Namespace are not handled by Knock but it should.

The only way to deal with this at the moment would be to do something like:

```ruby
before_action :authenticate_user

private

def authenticate_user
  authenticate_for V1::User
end
```

I'm open to suggestion on what would be a better way to handle this.

**Comment by ekampp** [comment]
Good question. 

Perhaps defining it somehow, like so: 

```ruby
knock_namespace :v1
before_action :authenticate_user
```

Or somehow using the `classify` inflection instead of the `camelize`, [here](https://github.com/nsarno/knock/blob/master/lib/knock/authenticable.rb#L35). But this approach requires the string to be `v1/user` instead of `v1_user` at this stage.

**Comment by sachse** [comment]
Is it possible to infer the namespace from the route name, perhaps?

**Comment by nsarno** [comment]
@sachse Interesting suggestion! I'll give it a try.

Agreed on keeping configuration minimal.

**Comment by nsarno** [comment]
After thinking about it, I don't see how that would be possible. The route has no relation with the user model you want to authenticate with.

**Comment by sachse** [comment]
Not necessarily, that's true. I'm only speaking for myself here, but I would assume that knock would look for the model in the same namespace the route is in.

For what it's worth I think that the current method of using `authenticate_for` works rather well as it is.

**Comment by ekampp** [comment]
In the case of a heavy namespace separated application the convention is to use a base controller and model and such per namespace. This means that configuring knock would only happen in that one, central location.

**Comment by nsarno** [comment]
@ekampp You can also define a method calling `authenticate_for` inside the base controller and use it in the before filter like in my first example. I agree with @sachse that it seems like a good enough solution.

I'm still happy to hear other suggestions on how to handle this but in the mean time I'll add this to the README and close this issue.

**Comment by alexkalish** [comment]
I'm trying to use knock 1.5 using namespaced models and I'm struggling to get the solution mentioned above to work.  With a model such as a `Admin::User`, calling `authenticate_for Admin::User` will generate `getter_name` of `current_admin/user` ([here](https://github.com/nsarno/knock/blob/master/lib/knock/authenticable.rb#L8)).  This will defined as a usable method on the controller, but can only be accessed via `#send`.  I'm also having trouble getting knock to actually restrict access with this configuration.  It appears to be permitting any request to be processed.

Any thoughts?

Thanks.
