### ISSUE TITLE
How to skip authenticate! some specific actions?

### ISSUE THREAD

**Issue by ricsdeol** [nsarno/knock#8]
Hello I'm trying skip athenticate method this way:

```ruby
skip_before_filter :authenticate, only: :half_hourly
and
skip_before_filter :authenticate!, only: :half_hourly
```

but this is not working.

Can you help me?

**Comment by nsarno** [comment]
[skip_before_filter](http://apidock.com/rails/ActionController/Filters/ClassMethods/skip_before_filter) is deprecated.

You can do this instead:

```
before_action :authenticate, except: [:half_hourly]
```

**Comment by ricsdeol** [comment]
Oh I forgot this, thanks!!!! @nsarno
