### ISSUE TITLE
404 on login response format

### ISSUE THREAD

**Issue by jalberto** [nsarno/knock#86]
by defualt knock returns 'json' in response format heade. I would like to return "application/vnd.api+json

I tried to costumiz eit with an after_action:

    response.content_type = "application/vnd.api+json"

but it doesn't work.

I creaed y own contrller for this, but will be great to add it as an option.

Thanks!

**Comment by nsarno** [comment]
You can add a before action in your token controller:

E.g.

```ruby
class UserTokenController < Knock::AuthTokenController
  before_action :set_content_type

  private

  def set_content_type
    self.content_type = "application/vnd.api+json"
  end
end
```
