### ISSUE TITLE
question: is there a generator that pulls the the *_token controller into the project?

### ISSUE THREAD

**Issue by AndrewLngdn** [nsarno/knock#87]
If not, I'd like to add that functionality. I love how lightweight gem is, but it would be easier to deal with if I could just pull chunks of it into my project. I'll make a PR if this doesn't exist

**Comment by nsarno** [comment]
There is a generator for the token controller

From the [README](https://github.com/nsarno/knock#installation):


> If you don't use an external authentication solution like Auth0, you also need to provide a way for users to sign in:

```
$ rails generate knock:token_controller user
```

> This will generate the controller user_token_controller.rb and add the required route to your config/routes.rb file. You can also provide another entity instead of user. E.g. admin

Is this what you were looking for?

**Comment by AndrewLngdn** [comment]
I meant a generator that actually pulls the relevant code into your project if you want to authenticate other routes for the same type of entity. I'll figure it out. Thanks!
