### ISSUE TITLE
Passing token from iOS app returns 401

### ISSUE THREAD

**Issue by brandonmanson** [nsarno/knock#90]
After several days of debugging and even nuking my repo and starting over, I still can't seem to get any authorization with a JWT token I'm passing from an iOS app authenticated with Auth0 Lock. After updating to Knock 1.5, I've narrowed it down to `self.from_token_payload` not creating a new user. Any assistance would be greatly appreciated! 
Here's my repo: [https://github.com/brandonmanson/happening-api](https://github.com/brandonmanson/happening-api)

**Comment by nsarno** [comment]
It would be helpful if you could provide a failing request spec for this issue.

Also, could you link to the documentation explaining which claims are passed through the payload in your case?

It seems like you expect the payload to contain a field `:email`. Are you sure this is valid? When reading [this](https://auth0.com/docs/quickstart/backend/rails), it seems like the user id is passed through the subject claim (i.e. `payload["sub"]`).

**Comment by brandonmanson** [comment]
Auth0 allows you to specify claims in [this documentation](https://auth0.com/docs/scopes). Here's what my payload looks like:

`"payload: {"email"=>"mansonbrandon@gmail.com", "email_verified"=>true, "iss"=>"https://brandonmanson.auth0.com/", "sub"=>"auth0|57843c212f0e1ca74ee67b60", "aud"=>"PGQxxDeLQBkABM5Pg6v1lOZgz2tLcTlU", "exp"=>1469081229, "iat"=>1469045229}"`

I was trying to use `find_or_create_by` with something other than `payload["sub"]` since I hadn't gotten that to work either.

I don't have a failing request spec yet. I am passing a valid token in an HTTP request from XCode Simulator. I'll come up with a way to mock that.

**Comment by nsarno** [comment]
I'll close this issue as it does not seem related to Knock directly but you can keep posting here and I'll be happy to help once we have a failing spec :)

**Comment by brandonmanson** [comment]
👍 thank you!
