### ISSUE TITLE
Unable to retrieve payload for an expired token

### ISSUE THREAD

**Issue by bmcdaniel11** [nsarno/knock#92]
When trying to retrieve a payload from an expired token, I get an expired token error message. I see this is because the default option is to verify the expiration date via the <code>:verify_expiration</code> key if a <code>:token_lifetime</code> has been specified. This works fine in most cases, but I need data from the jwt after it has expired. Currently, my workaround is to extend the AuthToken class and override the <code>verify_claims</code> method, but I think an <code>options</code> param in the initializer of the AuthToken would be acceptable. Something like this:

```
def initialize payload: {}, token: nil, verify_options: {}
  if token.present?
    @payload, _ = JWT.decode token, decode_key, true, options.merge(verify_options)
    @token = token
  else
    @payload = payload
    @token = JWT.encode claims.merge(payload),
    secret_key,
    Knock.token_signature_algorithm
  end
end
```

This would allow anyone to decide what keys are to be validated while compiling the payload. What are your thoughts on this?

**Comment by bmcdaniel11** [comment]
Add PR for suggested update https://github.com/nsarno/knock/pull/93

**Comment by alduro** [comment]
you can pass expiration time this way:

```
  exp = Time.now.to_i + 3.days # Token expiration
  token = Knock::AuthToken.new(payload: { sub: "#{role}|#{resource_id}", exp: exp }).token
```

**Comment by bmcdaniel11** [comment]
Yes, but I'm trying to retrieve the payload after the token has already expired. I have data I need to clear which is specific to the token, and since the `AuthToken.new` method automatically returns no payload if the token is expired, I can't get the data I need. Having a way to custom validate the token is what I am looking for. Being able to skip the expiration verification allows me to collect a payload even after a token has expired.

**Comment by alduro** [comment]
```
verify_lifetime: false 
```
within payload?

**Comment by bmcdaniel11** [comment]
I'm retrieving an existing AuthToken, not making a new one. The existing one has expired. When I retrieve it using the token, I get the error back that it has expired because it always validates the expiration. I only wish to skip the expiration validation to retrieve the payload from the expired AuthToken. Currently there is no way to skip validation on the expiration date if an expiration date exists. The PR would give the option of skipping it if the user needed the payload of an expired token.

**Comment by nsarno** [comment]
I understand what you're trying to achieve and the limitations. I'd like to understand your use case a bit more before deciding if this should be a feature or not. Could you give me an example of what data you're trying to get from the expired token?

Thank you for your patience. I've been away for a bit and unable to allocate a lot of time to reviewing PRs and issues.

**Comment by bmcdaniel11** [comment]
No worries on the time, I'm not in a rush on it. So for the use case, I have a `User` model and when the user signs in, I create an `Authentication` model to store other statistics of the log in, including salt so we can invalidate a token externally. Typically, when a user signs out, I delete the authentication, which works fine as I get the user from the Token payload, and I get the salt from the token payload to find the authentication. However, when a user signs out and the token has expired, I get an expired token error raised and do not have access to the payload to delete the authentication. Leaving an `Authentication` stale in the db and clearing it later isn't a huge deal, but I would like to think the payload would be accessible somehow, regardless of the validations of the token. There may be a better way of handling this, but since validation happens on the initialization of the `AuthToken`, I thought an optional hash to override default validations was simple way to approach it. Let me know if that clears things up a bit and thanks for taking the time to review.

**Comment by Carlows** [comment]
@bmcdaniel11 did you find a proper way to do what you described?

**Comment by Carlows** [comment]
Nevermind, just realized your PR was merged https://github.com/nsarno/knock/pull/93

However, you do you get the token payload in a request?
